language: node_js
node_js:
 - "stable"
install:
 - npm install -g ionic cordova
 - npm install --only=dev
after_success:
 - ionic cordova build browser --prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: www/
  keep-history: true
  on:
    branch: master
notifications:
  email: false